config/routes.rb
Rails.application.routes.draw do

        
  
  root 'tabs#home'

  get '/home', to: 'tabs#home', as: 'home'
  get '/story', to: 'tabs#story', as: 'story'
  get '/recipes', to: 'tabs#recipes', as: 'recipes'
  get '/faq', to: 'tabs#faq', as: 'faq'
  get '/contact', to: 'tabs#contact', as: 'contact'
  get '/privacy', to: 'tabs#privacy', as: 'privacy'
  get '/sessions', to: 'tabs#sessions', as: 'sessions'
  get '/terms', to: 'tabs#terms', as: 'terms'
  get '/contactus', to: 'contact_requests#new', as: 'new_contact_request'

  get '/contact_requests', to: 'contact_requests#index', as: 'contact_requests'
  post '/contact_requests', to: 'contact_requests#create'
  get '/contact_requests/:id', to: 'contact_requests#show', as: 'contact_request'
  get '/contact_requests/:id/edit', to: 'contact_requests#edit', as: 'edit_contact_request'
  patch '/contact_requests/:id', to: 'contact_requests#update'
  put '/contact_requests/:id', to: 'contact_requests#update'
  delete '/contact_requests/:id', to: 'contact_requests#destroy'

  mount Spree::Core::Engine, :at => '/store'
  

end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base

  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_format_of :phone, :with => /(\(|)\d{3}(\) |\)|\.|\-| |)\d{3}(\.|\-| |)\d{4}/i, :allow_blank => true
  validates :subject, presence: true
  validates :text, presence: true  

  def email_format
    self.email = self[:email].downcase
  end

  def name_format
    self.name = self[:name].titleize if self.name
  end

  def number_to_phone(number, options = {})
    return unless number
    options = options.symbolize_keys

    parse_float(number, true) if options.delete(:raise)
    ERB::Util.html_escape(ActiveSupport::NumberHelper.number_to_phone(number, options))
  end

  def phone_format
    self.phone = number_to_phone(self[:phone].gsub(/\D/, '').to_i, area_code: true) if self.phone
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  has_many :addresses
  has_many :carts
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :expire_hsts
  protect_from_forgery with: :exception


private
  def expire_hsts
    response.headers["Strict-Transport-Security"] = 'max-age=0'
  end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  include ApplicationHelper
  before_action :set_contact_request, only: [:show, :edit, :update, :destroy]
  # before_action :check_admin, except: [:new]
  http_basic_authenticate_with name: "kim", password: "sant's secret", except: [:new]
  
  

  def index
    @contact_requests = ContactRequest.all.where(resolved: false)
  end

  def show
  end

  def new
    @contact_request = ContactRequest.new
  end

  def edit
  end

  def create
    @contact_request = ContactRequest.new(contact_request_params)

    respond_to do |format|
      if @contact_request.save
        @contact_request.update(resolved: false)
        format.html { redirect_to home_path, notice: 'Thank you. We will address your concerns shortly.' }
        format.json { render :root, status: :created, location: @contact_request }
      else
        format.html { render :new }
        format.json { render json: @contact_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact_request.update(contact_request_params)
        format.html { redirect_to contact_requests_path, notice: 'Contact request was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_request }
      else
        format.html { render :edit }
        format.json { render json: @contact_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @contact_request.destroy
    @contact_request.update(resolved: true)
    respond_to do |format|
      format.html { redirect_to contact_requests_url, notice: 'Contact request was successfully resolved.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact_request
      @contact_request = ContactRequest.find(params[:id])
    end

    def contact_request_params
      params.require(:contact_request).permit(:name, :email, :phone, :subject, :text)
    end

    # def check_admin
    #   redirect_to home_path
    #   # true
    #   # return true if spree_current_user
    # end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController

	def home
	end

	def story
	end

	def recipes
	end

	def faq
	end

  def contact
  end

  def privacy
  end

  def sessions
  end

  def terms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_link_to(image_path, url, image_tag_options = { }, link_to_options = { })
    link_to url, link_to_options do
      image_tag image_path, image_tag_options
    end
  end
end

app/views/contact_requests/_form.html.erb
<%= form_for(@contact_request) do |f| %>
  <% if @contact_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_request.errors.count, "error") %> prohibited this contact_request from being saved:</h2>

      <ul>
      <% @contact_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.select :subject, options_for_select([["Info Request", "Info Request"], ["Billing Issue", "Billing Issue"], ["Technical Problem", "Technical Problem"], ["Contact Us", "Contact Us"]]), :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_requests/edit.html.erb
    <div class="page-header-image contact">&nbsp;
   
    </div>
    
    <h1>Editing Contact Request</h1>

<%= form_for(@contact_request) do |f| %>
  <% if @contact_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_request.errors.count, "error") %> prohibited this contact_request from being saved:</h2>

      <ul>
      <% @contact_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    Subject<br/>
    <%= @contact_request.subject %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', contact_requests_path %>

app/views/contact_requests/index.html.erb
    <div class="page-header-image contact">&nbsp;
   
    </div>
<h1>Listing Contact Requests</h1>

<div class="requests">
    <p>---------------------------------</p>
  <% @contact_requests.each do |contact_request| %>
    <div>
      <p>Name: <%= contact_request.name %><br/>
      Email: <%= contact_request.email %><br/>
      <% if contact_request.phone %>
        Phone: <%= contact_request.phone %><br/>
      <% end %>
      Subject: <%= contact_request.subject %><br/>
      Date: <%= contact_request.created_at %></p>
      <p>Issue:<br/><%= contact_request.text %></p>
      <p><%= link_to 'Show', contact_request %> 
        | 
        <%= link_to 'Edit', edit_contact_request_path(contact_request) %>
        |
        <%= link_to 'Resolved', contact_request, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <p>---------------------------------</p>
    </div>
  <% end %>
</div>

app/views/contact_requests/new.html.erb
    <!-- begin Contact Page -->
    <div class="page-header-image contact">&nbsp;
   
    </div>
    <div class="container page">    
    <h1>Contact Us</h1>    
      

      <%= form_for(@contact_request) do |f| %>
        <% if @contact_request.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@contact_request.errors.count, "error") %> prohibited this contact_request from being saved:</h2>

            <ul>
            <% @contact_request.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>

        <div class="field">
            <%= f.label :email %><br>
          <% if spree_current_user == nil %>
            <%= f.text_field :email %>
          <% else %>
            <%= f.text_field :email, value: "#{spree_current_user.email}" %>
          <% end %>
        </div>
        <div class="field">
          <%= f.label :phone %><br>
          <%= f.text_field :phone %>
        </div>
        <div class="field">
          <%= f.label :subject %><br>
          <%= f.select :subject, options_for_select([["Info Request", "Info Request"], ["Billing Issue", "Billing Issue"], ["Technical Problem", "Technical Problem"], ["Contact Us", "Contact Us"]]), :include_blank => true %>
        </div>
        <div class="field">
          <%= f.label :text %><br>
          <%= f.text_area :text %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
     
    </div>  
    <!-- end Contact Page -->

app/views/contact_requests/show.html.erb
    <div class="page-header-image contact">&nbsp;
   
    </div>
<p>
  <strong>Name:</strong>
  <%= @contact_request.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_request.email %>
</p>

<% if @contact_request.phone %>
  <p>
    <strong>Phone:</strong>
    <%= @contact_request.phone %>
  </p>
<% end %>

<p>
  <strong>Subject:</strong>
  <%= @contact_request.subject %>
</p>

<p>
  <strong>Text:</strong>
  <%= @contact_request.text %>
</p>

<%= link_to 'Edit', edit_contact_request_path(@contact_request) %> |
<%= link_to 'Back', contact_requests_path %>

app/views/layouts/_footer.html.erb
    <!--Begin Footer -->
    <footer>
        <div class="footer-logo">
          <%= image_tag "sant-logo.png", alt: "Sant" %>        </div>
        <div class="row-no-margin footer-social">
            <div class="container">
                <div class="row">
                    <div class="col-3">
                        <a href="https://www.facebook.com/idrinksant" class="icon" target="_blank"> <i class="fa fa-facebook"></i>
                        </a>
                    </div>
                    <div class="col-3">
                        <a href="https://twitter.com/idrinksant" class="icon" target="_blank"> <i class="fa fa-twitter"></i> </a>
                    </div>
                    <div class="col-3">
                        <a href="https://instagram.com/idrinksant" class="icon" target="_blank"> <i class="fa fa-instagram"></i>
                        </a>
                    </div>
                    <div class="col-3"><a href="http://pinterest.com/idrinksant" class="icon" target="_blank"><i class="fa fa-pinterest-p"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row-no-margin footer-nav">
            <div class="container">
                <div class="col-12 ">
                    <ul>
                        <li>
                          <%= link_to "Shop", spree_path %>
                        </li>
                        <li>
                          <%= link_to "Our Story", story_path %>
                        </li>
                        <li>
                          <%= link_to "Sant Sessions" , sessions_path %>
                        </li>
                        <li>
                          <%= link_to "Recipes", recipes_path %>
                        </li>
                        <li>
                          <%= link_to "FAQs", faq_path %>
                        </li>
                        <li>
                          <%= link_to "Contact Us", new_contact_request_path %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row-no-margin footer-legal">
            <div class="container">
                <div class="col-12">
                    <ul>
                        <li>
                          <%= link_to "Terms of Usage", terms_path %>
                        </li>
                        <li>
                          <%= link_to "Privacy Policy", privacy_path %>
                        </li>
                    </ul>
                </div>
                <div class="col-12">
                    <p class="copyright">&copy;2014-2015 Sant. All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<!Doctype html>
<html>
<head>
    <title>Sant - The Infusable Superfruit</title>
    <meta name="description" content="The dried superfruit that transforms into a fresh beverage.">
    <meta name="keywords" content="Sant, idrinksant, superfruit beverage, superfruit recipe, superfood, yoga, superfruit tea">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="css/style.css" media="screen, projection" rel="stylesheet" type="text/css" />
</head>
<body>
    <a id="top"></a>

app/views/layouts/_navbar.html.erb
<!--Begin Top Navigation -->
    <div class="container-flex navbar">
        <div class="container nav">
            <div class="row">
                <div class="col-2 nav-logo">
                    <%= image_link_to "sant-logo.png", home_path %>
                </div>
                <div class="col-1"></div>
                <div class="col-9">
                    <ul class="nav-main">
                        <li>
                          <%= link_to "Shop Sant", spree_path %>
                        </li>
                        <li>&#8226;</li>
                        <li>
                          <%= link_to "Our Story", story_path %>
                        </li>
                        <li>&#8226;</li>
                        <li>
                          <%= link_to "Sant Sessions", sessions_path %>
                        </li>
                        <li>&#8226;</li>
                        <li>
                          <%= link_to "Recipes", recipes_path %>
                        </li>
                        <li>&#8226;</li>
                        <li>
                          <%= link_to "FAQs", faq_path %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Toggle Responsive Menu for smaller screens -->
    <div class="mobile-nav">
        <div class="mobile-logo">
            <%= image_link_to "sant-logo.png", "/home.html" %>
        </div>
        <div class="menu-btn" id="menu-btn">
            <div></div>
            <span></span>
            <span></span>
            <span></span>
        </div>
        <div class="responsive-menu">
            <ul>
                <li>
                  <%= link_to "Shop Sant", spree_path %>
                </li>
                <li>
                  <%= link_to "Our Story", story_path %>
                </li>
                <li>
                  <%= link_to "Sant Sessions", sessions_path %>
                </li>
                  <%= link_to "Recipes", recipes_path %>
                </li>
                  <%= link_to "FAQs", faq_path %>
                </li>
            </ul>
        </div>
    </div>

app/views/layouts/application.html.erb
<!Doctype html>
<html>

<head>
    <title>Sant - The Infusable Superfruit</title>
    <meta name="description" content="The dried superfruit that transforms into a fresh beverage.">
    <meta name="keywords" content="Sant, idrinksant, superfruit beverage, superfruit recipe, superfood, yoga, superfruit tea">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>

<body>
    <a id="top"></a>
    
    <%= render "layouts/navbar" %>

    <%= yield %>

    <%= render "layouts/footer" %>

    <!--back to top -->
    <a href="#top" class="cd-top smoothScroll">Top</a>

    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MKRP2D"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MKRP2D');</script>
    <!-- End Google Tag Manager -->
</body>

</html>

app/views/tabs/contact.html.erb
    <!-- begin Contact Page -->
    <div class="page-header-image contact">&nbsp;
   
    </div>
    <div class="container page">    
    <h1>Contact Us</h1>    
      
      <%= render 'contact_requests/form' %>
     
    </div>  
    <!-- end Contact Page -->

app/views/tabs/home.html.erb
 <!--Begin Slider -->
 <div class="container-flex ">
     <div class="gallery autoplay items-4">
         <div id="item-1" class="control-operator"></div>
         <div id="item-2" class="control-operator"></div>
         <div id="item-3" class="control-operator"></div>
         <div id="item-4" class="control-operator"></div>
         <!-- Slide 1 -->
         <figure class="item ">
             <div class="slide-1">
                 <div class="container">
                     <div class="row-no-margin">
                         <div class="col-6"></div>
                         <div class="col-6">
                             <div class="vc-slider-caption caption">
                                 <div>
                                     <p>The
                                         <br /> <span>superfruit</span>
                                         <br /> that infuses into a fresh
                                         <br /><span>beverage</span>.</p>
                                     <p>
                                         <%= link_to "Order Me", spree_path %>
                                     </p>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </figure>
         <!-- Slide 2 -->
         <figure class="item">
             <div class="slide-2">
                 <div class="container">
                     <div class="row-no-margin">
                         <div class="col-12">
                             <div class="caption">
                                 <p><span>Garcinia Indica</span>
                                 </p>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </figure>
         <!-- Slide 3 -->
         <figure class="item">
             <div class="slide-3">
                 <div class="container">
                     <div class="row-no-margin">
                         <div class="col-12">
                             <div class="bottom caption">
                                 <p><span>Infuse It</span>
                                 </p>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </figure>
         <!-- Slide 4 -->
         <figure class="item">
             <div class="slide-4">
                 <div class="container">
                     <div class="row-no-margin">
                         <div class="col-6">
                         </div>
                         <div class="col-6">
                             <div class="vc-slider-caption caption">
                                 <div>
                                     <p class="caption-boxed"><span>Endless Possibilities</span>
                                     </p>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </figure>

         <!-- Bullets -->
         <div class="controls">
             <a href="#item-1" class="control-button">&#8226;</a>
             <a href="#item-2" class="control-button">&#8226;</a>
             <a href="#item-3" class="control-button">&#8226;</a>
             <a href="#item-4" class="control-button">&#8226;</a>
         </div>
     </div>
 </div>

 <!-- Begin Simple, Super Healthy, Sustainable, Sant Menu -->
    <div class="container-centered">
        <div class="row second-menu">
            <div class="col-3 second-menu-item">
                <a href="#simple" class="smoothScroll icon "><span class="icon-simple"></span>Simple
                    </a>
            </div>
            <div class="col-3 second-menu-item">
                <a href="#super-healthy" class="smoothScroll icon"><span class="icon-super-healthy"></span>Super Healthy
                    </a>
            </div>
            <div class="col-3 second-menu-item">
                <a href="#sustainable" class="smoothScroll icon"><span class="icon-sustainable"></span>Sustainable
                    </a>
            </div>
            <div class="col-3 second-menu-item">
                <a href="#sant" class="smoothScroll icon"><span class="icon-sant"></span>Sant
                    </a>
            </div>
        </div>
    </div>

    <!-- begin Simple section -->
    <div class="container section">
        <a class="anchor" id="simple"></a>
        <div class="row">
            <div class="col-5">
                <h1>Simple</h1>
                <h3>One ingredient that you add to water</h3>
                <p>Healthy really can be this easy</p>
                <div class="illustration">
                  <%= image_tag "sant-formula.png", alt: "Garcinia Indica + Water = Refreshign Fruit Infusion" %>
                </div>
            </div>
            <div class="col-2"></div>
            <div class="col-5">
                <%= image_tag "circle-simple-1.png", class: "circle-img" %>
            </div>
        </div>
        <div class="row">
            <div class="col-6"></div>
            <div class="col-3">
              <%= image_tag "circle-simple-2.png", class: "circle-img" %>
            </div>
            <div class="col-3"></div>
        </div>
        <div class="row">
            <div class="col-5">
                <div class="slideshow">
                    <div>
                      <%= image_tag "circle-simple-3-gallery-1.png" %>
                    </div>
                    <div>
                      <%= image_tag "circle-simple-3-gallery-2.png" %>
                    </div>
                    <div>
                      <%= image_tag "circle-simple-3-gallery-3.png" %>
                    </div>
                    <div>
                      <%= image_tag "circle-simple-3-gallery-4.png" %>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
            <div class="col-5">
                <h3>Customize it</h3>
                <p>Make a light pink infusion for a subtle rose taste, a dark red infusion for a cranberry-like flavor or a sweet option by adding honey or brown sugar.</p>

                <p>When you&rsquo;re re feeling adventurous, use your infusion for hot teas, organic sodas, smoothies, juices, or cocktails. Sant-gria is a party favorite. </p>
                <div class="illustration">
                  <%= image_tag "sant-styles.png", alt: "Customize your beverage" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-5">&nbsp;
            </div>
            <div class="col-4">
              <%= image_tag "circle-simple-4.png", class: "circle-img" %>
            </div>
            <div class="col-3">&nbsp;</div>
        </div>
    </div>


    <!-- begin Super Healthy section -->
    <div class="container section">
        <a class="anchor" id="super-healthy"></a>
        <div class="row">
            <div class="col-5">
                <h1>Super Healthy</h1>
                <h3><span class="number">5</span>X more antioxidants than Kale  </h3>
                <p>These super powerful antioxidants &mdash; Garcinol, HCA and Xanthones &mdash; help restore balance to the mind and body.</p>
                <ul class="fa-ul benefits">
                    <li><i class="fa-li fa fa-plus"></i>Promotes digestion</li>
                    <li><i class="fa-li fa fa-plus"></i>Fights bacteria</li>
                    <li><i class="fa-li fa fa-plus"></i>Prevents infections and cell deterioration</li>
                    <li><i class="fa-li fa fa-plus"></i>Regulates sleep and mood</li>
                    <li><i class="fa-li fa fa-plus"></i>Manages weight and increases muscle tone</li>
                    <li><i class="fa-li fa fa-plus"></i>Neutralizes PH levels</li>
                    <li class="plus"><i class="fa-li fa fa-plus"></i>Decreases inflamation</li>
                    <li><i class="fa-li fa fa-plus"></i>Cleanses skin</li>
                    <li><i class="fa-li fa fa-plus"></i>Strengthens the heart and stabilizes cholesterol</li>
                </ul>
                <p>Garcinia indica has been used in Ayurveda for centuries to prevent and treat illnesses.</p>
            </div>
            <div class="col-2"></div>
            <div class="col-5">
                <%= image_tag "circle-super-healthy-1.png", class: "circle-img"%>
            </div>
        </div>
        <div class="row">
            <div class="col-5">
                <%= image_tag "circle-super-healthy-2.png", class: "circle-img"%>
            </div>
            <div class="col-2">&nbsp;</div>
            <div class="col-5">
                <h3>All Natural.</h3>
                <p> Tons of good stuff; no bad stuff</p>
                <ul class="benefits fa-ul">
                    <li><i class="fa-li fa fa-plus"></i>Organically grown and naturally sun-dried. No preservatives</li>
                    <li><i class="fa-li fa fa-plus"></i>Vitamins B &amp; C, potassium, manganese &amp; magnesium</li>
                    <li><i class="fa-li fa fa-plus"></i>Only 5 calories and 3 grams of sugar</li>
                    <li><i class="fa-li fa fa-plus"></i>No added dyes or flavors. No additives, period.</li>
                </ul>
                <div class="healthy-icons">
                    <div>
                      <%= image_tag "organic.png", alt: "organic" %>
                    </div>
                    <div>
                      <%= image_tag "non-gmo.png", alt: "non-gmo" %>
                    </div>
                    <div>
                      <%= image_tag "vegan.png", alt: "vegan" %>
                    </div>
                    <div>
                      <%= image_tag "gluten-free.png", alt: "gluten free" %>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-5">&nbsp;
            </div>
            <div class="col-4">
              <%= image_tag "circle-super-healthy-3.png", class: "circle-img", alt: "Runner tying shoes with Sant bottle" %>
            </div>
            <div class="col-3">&nbsp;</div>
        </div>
    </div>

    <!-- Begin Sustainable Section -->
    <div class="container section-2">
        <a class="anchor" id="sustainable"></a>
        <div class="row">
            <div class="col-5">
                <h1>Sustainable</h1>
                <h3>Working directly with farmers and women&rsquo;s empowerment groups in India</h3>
                <p>60% of the Garcinia indica crop once went to waste each year, yet the farming families in these rural communities weren&rsquo;t able to make a sufficient living.</p>
                <p> Not anymore. Now, working with Sant, families are able to harvest Garcinia indica. You get a super healthy beverage and communities get vital livelihood opportunities. </p>
            </div>
            <div class="col-2"></div>
            <div class="col-5">
              <%= image_tag "circle-sustainable-1.png", class: "circle-img", alt: "Happy Farmer" %>
            </div>
        </div>
        <div class="row">
            <div class="col-5">
                <%= image_tag "circle-sustainable-2.png", class: "circle-img", alt: "Reusable Bottles" %>
            </div>
            <div class="col-2"></div>
            <div class="col-5">
                <h3>Drinking from re-useable bottles</h3>
                <p>Disposable bottles are a problem. And you&rsquo;re a problem solver. So with Sant, you get to enjoy beverages from your re-useable glass or bottle. It&rsquo;s healthier for you and your environment. </p>
                <div class="illustration">
                  <%= image_tag "sustainable-bottles.png", alt: "1 pouch + Your re-usable bottle or glass = Up to 100 disposable bottles" %>
                </div>
            </div>
        </div>
    </div>


    <!-- Begin Sant section -->
    <div class="container-flex balance">
        <div class="container">
            <a class="anchor" id="sant"></a>
            <div class="row">
                <div class="row-no-margin">
                    <div class="col-5">
                    </div>
                    <div class="col-2">&nbsp;</div>
                    <div class="col-5">
                        <div class="vc-balance">
                            <div>
                                <h1>Sant</h1>
                                <h3>Balance in minds bodies communities and the environment</h3>
                                <p>Sant is short for Santulan, which means balance. We didn&rsquo;t pick balance just because we like standing on our heads. The name fits since we create experiences that promote balance in minds, bodies, communities, and the environment</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>