spree_account_recurring/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :recurrings, except: :show do
      resources :plans, except: :show
    end

    resources :subscriptions, only: :index
    resources :subscription_events, only: :index
  end

  resources :recurring_hooks, only: :none do
    post :handler, on: :collection
  end

  namespace :recurring do
    resources :plans, only: :index do
      resources :subscriptions, only: [:show, :create, :destroy, :new]
    end
  end
end

spree_account_recurring/app/models/concerns/spree/plan/api_handler.rb
module Spree
  class Plan < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        before_validation :set_api_plan_id, on: :create
        after_create :create_plan
        after_update :delete_plan, :if => [:deleted_at_changed?, :deleted_at?]
        after_update :update_plan, :if => :name_changed?
      end

      def create_plan
        provider.create_plan(self)
      end

      def delete_plan
        provider.delete_plan(self)
      end

      def update_plan
        provider.update_plan(self)
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error: #{e.message}"
          errors.add :base, e.message
          false
        end
      end

      def provider
        recurring.present? ? recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private

      def set_api_plan_id
        provider.set_api_plan_id(self)
      end
    end
  end
end

spree_account_recurring/app/models/spree/plan.rb
module Spree
  class Plan < ActiveRecord::Base
    include RestrictiveDestroyer
    include ApiHandler

    acts_as_restrictive_destroyer

    belongs_to :recurring
    has_many :subscriptions

    validates :amount, :interval, :interval_count, :name, :currency, :recurring_id, :api_plan_id, presence: true
    attr_readonly :amount, :interval, :currency, :id, :trial_period_days, :interval_count, :recurring_id, :api_plan_id

    before_validation :manage_default, if: :default_changed?

    scope :active, -> { undeleted.where(active: true) }
    scope :visible, -> { active.joins(:recurring).where(["spree_recurrings.active = ? AND spree_recurrings.deleted_at IS NULL", true]) }

    def visible?
      active? && !is_destroyed? && recurring.visible?
    end

    def manage_default
      recurring.plans.undeleted.where.not(id: id).update_all(default: false)
    end

    def self.default
      visible.find_by(default: true)
    end
  end
end

spree_account_recurring/app/controllers/spree/admin/plans_controller.rb
module Spree
  module Admin
    class PlansController < Spree::Admin::BaseController
      before_action :load_recurring
      before_action :find_plan, :only => [:edit, :destroy, :update]

      def index
        @plans = Spree::Plan.undeleted.order('id desc')
      end

      def new
        @plan = @recurring.plans.build
      end

      def create
        @plan = @recurring.plans.build(plan_params)
        if @plan.save_and_manage_api
          flash[:notice] = 'Plan created successfully.'
          redirect_to edit_admin_recurring_plan_path(@recurring, @plan)
        else
          render :new
        end
      end

      def update
        if @plan.save_and_manage_api(plan_params(:update))
          flash[:notice] = 'Plan updated successfully.'
          redirect_to edit_admin_recurring_plan_path(@recurring, @plan)
        else
          render :edit
        end
      end
      
      def destroy
        @plan.restrictive_destroy_with_api
      end

      private

      def load_recurring
        unless @recurring = Spree::Recurring.undeleted.where(id: params[:recurring_id]).first
          flash[:error] = "Recurring not found."
          redirect_to admin_recurrings_path
        end
      end

      def plan_params(action=:create)
        if action == :create
          params.require(:plan).permit(:name, :trial_period_days, :interval, :currency, :amount, :active, :interval_count, :default)
        else
          params.require(:plan).permit(:name, :active, :default)
        end
      end

      def find_plan
        unless @plan = @recurring.plans.undeleted.where(id: params[:id]).first
          flash[:error] = "Plan not found."
          redirect_to admin_recurring_plans_path(@recurring)
        end
      end
    end
  end
end

spree_account_recurring/app/controllers/spree/plans_controller.rb
module Spree
  class PlansController < StoreController
    def index
      @plans = Spree::Plan.visible.order('id desc')
    end
  end
end

spree_account_recurring/app/views/spree/admin/plans/_form.html.erb
<div data-hook="admin_plan_form_fields">

  <div data-hook="plan">
    <div class="alpha four columns">
      <div class="field">
        <%= f.label :interval, Spree.t(:interval) %>
        <%= f.select :interval, @recurring.class::INTERVAL.collect{|k, v| [v, k]}, {}, {:disabled => @plan.persisted?, class: 'select2 fullwidth'} %>
      </div>

      <div class="field">
        <%= f.label :interval_count, Spree.t(:every) %>
        <%= f.select :interval_count, (1..11).collect {|i| [i, i]}, {}, {:disabled => @plan.persisted?, class: 'select2 fullwidth'} %>
      </div>

      <div class="field">
        <%= f.label :currency, Spree.t(:currency) %>
        <%= f.select :currency, @recurring.class::CURRENCY.collect{|k, v| [v, k]}, {}, {:disabled => @plan.persisted?, class: 'select2 fullwidth'} %>
      </div>
    </div>

    <div class="omega eight columns">
      <div class="field">
        <%= f.label :name, Spree.t(:name) %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :amount, Spree.t(:amount) %>
        <%= f.text_field :amount, :disabled => @plan.persisted? %>
      </div>

      <div class="field">
        <%= f.label :trial_period_days, Spree.t(:trial_period_days) %>
        <%= f.text_field :trial_period_days, :disabled => @plan.persisted? %>
      </div>

      <div class="field">
        <%= f.label :active, Spree.t(:active) %>
        <%= f.check_box :active %>&nbsp;&nbsp;&nbsp;&nbsp;
        <%= f.label :default, Spree.t(:default) %>
        <%= f.check_box :default %>
      </div>
    </div>
  </div>
</div>

<div class="clear"></div>

spree_account_recurring/app/views/spree/admin/plans/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_plan) %> <i class="icon-arrow-right"></i> <%= @plan.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_plans_list), admin_recurring_plans_path(@recurring), :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @plan } %>

<%= form_for @plan, :url => admin_recurring_plan_url(@recurring, @plan) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t('actions.update'), 'icon-ok' %>
    </div>
  </fieldset>
<% end %>

spree_account_recurring/app/views/spree/admin/plans/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_recurring) %> <i class="icon-arrow-right"></i> <%= @recurring.name %> <i class="icon-arrow-right"></i> <%= Spree.t(:plans) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_plan), new_admin_recurring_plan_path(@recurring), :icon => 'icon-plus', :id => 'admin_new_recurring_plans_link' %>
  </li>
<% end %>

<% if @plans.present? %>
  <table class="index" id='listing_recurring_plans'>
    <colgroup>
      <col style="width: 10%">
      <col style="width: 15%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 5%">
      <col style="width: 5%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_recurring_plans_index_headers">
        <th><%= Spree.t(:api_plan_id) %></th>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:amount) %></th>
        <th><%= Spree.t(:interval) %></th>
        <th><%= Spree.t(:interval_count) %></th>
        <th><%= Spree.t(:currency) %></th>
        <th><%= Spree.t(:trial_period_days) %></th>
        <th><%= Spree.t(:active) %></th>
        <th><%= Spree.t(:default) %></th>
        <th data-hook="admin_recurring_plans_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @plans.each do |plan|%>
        <tr id="<%= spree_dom_id plan %>" data-hook="admin_recurring_plans_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= plan.api_plan_id %></td>
          <td class="align-center"><%= plan.name %></td>
          <td class="align-center"><%= plan.amount %></td>
          <td class="align-center"><%= @recurring.class::INTERVAL[plan.interval.to_sym] %></td>
          <td class="align-center"><%= plan.interval_count %></td>
          <td class="align-center"><%= @recurring.class::CURRENCY[plan.currency.to_sym] %></td>
          <td class="align-center"><%= plan.trial_period_days %></td>
          <td class="align-center"><%= plan.active ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td class="align-center"><%= plan.default ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td data-hook="admin_recurring_plans_index_row_actions" class="actions">
            <%= link_to_edit_url edit_admin_recurring_plan_url(@recurring, plan), :no_text => true %>
            <%= link_to_delete plan, url: admin_recurring_plan_url(@recurring, plan), :no_text => true  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/plan')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_recurring_plan_path(@recurring) %>!
  </div>
<% end %>

<div data-hook="buttons" class="filter-actions actions">
  <%= button_link_to Spree.t(:back), edit_admin_recurring_url(@recurring) %>
</div>

spree_account_recurring/app/views/spree/admin/plans/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_plan) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_plans_list), admin_recurring_plans_path(@recurring), :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @plan } %>

<%= form_for @plan, :url => admin_recurring_plans_path(@recurring) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t(:create), 'icon-ok' %>
    </div>
  </fieldset>
<% end %>