spree_account_recurring/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :recurrings, except: :show do
      resources :plans, except: :show
    end

    resources :subscriptions, only: :index
    resources :subscription_events, only: :index
  end

  resources :recurring_hooks, only: :none do
    post :handler, on: :collection
  end

  namespace :recurring do
    resources :plans, only: :index do
      resources :subscriptions, only: [:show, :create, :destroy, :new]
    end
  end
end

spree_account_recurring/app/models/concerns/spree/subscription/api_handler.rb
module Spree
  class Subscription < ActiveRecord::Base
    module ApiHandler
      extend ActiveSupport::Concern

      included do
        attr_accessor :card_token
        before_create :subscribe
        before_update :unsubscribe, :if => [:unsubscribed_at_changed?, :unsubscribed_at?]
      end

      def subscribe
        provider.subscribe(self)
        self.subscribed_at = Time.current
      end

      def unsubscribe
        provider.unsubscribe(self)
      end

      def save_and_manage_api(*args)
        begin
          new_record? ? save : update_attributes(*args)
        rescue provider.error_class, ActiveRecord::RecordNotFound => e
          logger.error "Error while subscribing: #{e.message}"
          errors.add :base, "There was a problem with your credit card"
          false
        end
      end

      def provider
        plan.try(:recurring).present? ? plan.recurring : (raise ActiveRecord::RecordNotFound.new("Provider not found."))
      end

      private
    end
  end
end

spree_account_recurring/app/models/concerns/spree/subscription/role_subscriber.rb
module Spree
  class Subscription < ActiveRecord::Base
    module RoleSubscriber
      extend ActiveSupport::Concern

      included do
        before_create :add_role_subscriber, :unless => :unsubscribed_at?
        before_update :remove_role_subscriber, :if => :unsubscribed_at?
      end

      def add_role_subscriber
        if role = subscriber_role
          user.spree_roles << role
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      def remove_role_subscriber
        if role = subscriber_role
          user.spree_roles.destroy(role)
        else
          errors.add :base, "Subscriber role is not present."
          false
        end
      end

      private

      def subscriber_role
        Spree::Role.where(name: 'subscriber').first
      end
    end
  end
end

spree_account_recurring/app/models/spree/subscription.rb
module Spree
  class Subscription < ActiveRecord::Base
    include RoleSubscriber
    include RestrictiveDestroyer
    include ApiHandler

    acts_as_restrictive_destroyer column: :unsubscribed_at
    attr_accessor :card_token

    belongs_to :plan
    belongs_to :user
    has_many :events, class_name: 'Spree::SubscriptionEvent'

    validates :plan_id, :email, :user_id, presence: true
    validates :plan_id, uniqueness: { scope: [:user_id, :unsubscribed_at] }
    validates :user_id, uniqueness: { scope: :unsubscribed_at }

    delegate_belongs_to :plan, :api_plan_id
    before_validation :set_email, on: :create

    validate :verify_plan, on: :create

    private

    def set_email
      self.email = user.try(:email)
    end

    def verify_plan
      errors.add :plan_id, "is not active." unless plan.try(:visible?)
    end
  end
end

spree_account_recurring/app/controllers/spree/admin/subscriptions_controller.rb
module Spree
  module Admin
    class SubscriptionsController < Spree::Admin::BaseController
      include RansackDateSearch
      ransack_date_searchable date_col: 'subscribed_at'

      def index
        @search = Spree::Subscription.ransack(params[:q])
        @subscriptions = @search.result.includes(plan: :recurring).references(plan: :recurring).page(params[:page]).per(15)
        respond_with(@subscriptions)
      end
    end
  end
end

spree_account_recurring/app/controllers/spree/subscriptions_controller.rb
module Spree
  class SubscriptionsController < StoreController
    prepend_before_filter :load_object
    before_action :find_active_plan, only: [:new, :create]
    before_action :find_plan, only: [:show, :destroy]
    before_action :find_subscription, only: [:show, :destroy]
    before_action :authenticate_subscription, only: [:new, :create]

    def new
      @subscription = @plan.subscriptions.build
    end

    def create
      @subscription = @plan.subscriptions.build(subscription_params.merge(user_id: spree_current_user.id))
      if @subscription.save_and_manage_api
        redirect_to recurring_plan_subscription_url(@plan, @subscription), notice: "Thank you for subscribing!"
      else
        render :new
      end
    end

    def destroy
      if @subscription.save_and_manage_api(unsubscribed_at: Time.current)
        redirect_to recurring_plans_path, notice: "Subscription has been cancelled."
      else
        render :show
      end
    end

    private

    def find_active_plan
      unless @plan = Spree::Plan.active.where(id: params[:plan_id]).first
        flash[:error] = "Plan not found."
        redirect_to recurring_plans_url
      end
    end

    def find_plan
      unless @plan = Spree::Plan.where(id: params[:plan_id]).first
        flash[:error] = "Plan not found."
        redirect_to recurring_plans_url
      end
    end

    def find_subscription
      unless @subscription = @plan.subscriptions.undeleted.where(id: params[:id]).first
        flash[:error] = "Subscription not found."
        redirect_to root_url
      end
    end

    def subscription_params
      params.require(:subscription).permit(:email, :card_token)
    end

    def load_object
      @user ||= spree_current_user
      authorize! params[:action].to_sym, @user
    end

    def authenticate_subscription
      if subscription = spree_current_user.subscriptions.undeleted.first
        flash[:alert] = "You have already subscribed."
        redirect_to recurring_plan_subscription_url(@plan, subscription)
      end
    end
  end
end

spree_account_recurring/app/views/spree/admin/subscriptions/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:subscription) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class => 'button' %></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:subscription_date_search) %>
<% end %>

<% content_for :table_filter do %>
  <%= search_form_for @search, :url => spree.admin_subscriptions_url  do |s| %>
    <div class="date-range-filter field align-center">
      <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
      <%= s.text_field :subscribed_at_gt, :class => 'datepicker datepicker-from', :value => datepicker_field_value(params[:q][:subscribed_at_gt]) %>
      
      <span class="range-divider">
        <i class="icon-arrow-right"></i>
      </span>

      <%= s.text_field :subscribed_at_lt, :class => 'datepicker datepicker-to', :value => datepicker_field_value(params[:q][:subscribed_at_lt]) %>
      <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="date-range-filter field align-center">
      <%= label_tag nil, Spree.t(:email), :class => 'inline' %>
      <%= s.text_field :email_eq, style: "width:240px" %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
  <% end %>
<% end %>

<% if @subscriptions.any? %>
  <table class="index" id='listing_subscriptions'>
    <colgroup>
      <col style="width: 30%">
      <col style="width: 20%">
      <col style="width: 15%">
      <col style="width: 15%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="admin_subscriptions_index_headers">
        <th><%= Spree.t(:email) %></th>
        <th><%= Spree.t(:plan) %></th>
        <th><%= Spree.t(:subscribed_at) %></th>
        <th><%= Spree.t(:unsubscribed_at) %></th>
        <th data-hook="admin_recurring_plans_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @subscriptions.each do |subscription|%>
        <tr data-hook="admin_subscriptions_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= subscription.email %></td>
          <td class="align-center"><%= link_to subscription.plan.api_plan_id, edit_admin_recurring_plan_url(subscription.plan.recurring, subscription.plan) %></td>
          <td class="align-center"><%= subscription.subscribed_at.try(:strftime, '%d-%h-%Y') %></td>
          <td class="align-center"><%= subscription.unsubscribed_at.try(:strftime, '%d-%h-%Y') || 'N/A' %></td>
          <td data-hook="admin_recurring_plans_index_row_actions" class="actions">
            <%= link_to Spree.t(:view_events), admin_subscription_events_url(q: {subscription_email_eq: subscription.email}) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= paginate @subscriptions %>
<% else %>
  <div class="alpha sixteen columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/subscription')) %>
  </div>
<% end %>